name: CI

on:
  pull_request:
    paths:
      - 'app/**'
      - 'src/**'
      - 'components/**'
      - 'styles/**'
      - 'public/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
      - 'vite.config.*'
      - 'tailwind.config.*'
      - 'postcss.config.*'
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-and-visual:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Typecheck / Lint (best-effort)
        run: |
          npm run typecheck --if-present || true
          npm run lint --if-present || true

      - name: Build (if present)
        run: npm run build --if-present

      # ---- Vitest ----
      - name: Unit tests
        run: npm test -- --run

      # ---- Playwright (Chromium only) ----
      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: E2E / Visual tests (Chromium)
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload test results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: ignore
